name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilar e Executar Testes Unitarios
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: xabum_db
          MYSQL_ROOT_PASSWORD: pipeline-password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -ppipeline-password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Mensagem de inicio
        run: echo "Crianças n ouvi direito"

      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Preparar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Liberar Maven Wrapper
        run: chmod +x mvnw

      - name: Executar Testes e Build com Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/xabum_db?createDatabaseIfNotExist=true&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: pipeline-password
          XABUM_SECURITY_ENABLED: "false"
        run: ./mvnw clean package

      - name: Mensagem final
        run: echo "Estamos prontos capitão"